services:

  discovery_clickhouse:
    image: clickhousedb
    container_name: clickhousedb
    hostname: clickhousedb
    networks:
      - test_network
    ports:
      - "8123:8123"
      #- "9000:9000"
    volumes:
      - ./volumes/clickhouse_db:/var/lib/clickhouse 
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=app_database
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_local
    hostname: redis
    networks:
      - test_network
    command: redis-server --requirepass teste
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis_data:/data
    restart: unless-stopped

networks:
  test_network:
    external: true

