x-clickhouse-env: &clickhouse-env
  CLICKHOUSE_USER: ${CLICKHOUSE_USER}
  CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
  CLICKHOUSE_SCHEMA: ${CLICKHOUSE_SCHEMA}

services:
  clickhouse_gateway_api:
    image: clickhouse_gateway_api:latest
    container_name: clickhouse_gateway_api
    ports:
      - "8080:8080"
    environment:
      <<: *clickhouse-env
      TENANT_ID: ${TENANT_ID}
      AUDIENCE_JWT: ${AUDIENCE_JWT}

      CLICKHOUSE_HOSTNAME: clickhousedb
      CLICKHOUSE_PORT: 8123
      QUEUE_SIZE_LIMITER: 50

      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOSTNAME: redis
      REDIS_DB: 0

      INVALIDATE_CACHE_TOKEN: ${INVALIDATE_CACHE_TOKEN}

      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_INSECURE: "true"
    depends_on:
      clickhousedb:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started
    restart: unless-stopped
    networks:
      - test_network
    volumes:
      - ../schema_guids.json:/schema_guids.json:ro

  clickhousedb:
    image: clickhousedb
    container_name: clickhousedb
    hostname: clickhousedb
    networks:
      - test_network
    ports:
      - "8123:8123"
    volumes:
      - ./volumes/clickhouse_db:/var/lib/clickhouse 
    environment:
      <<: *clickhouse-env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - test_network
    command: tunnel --no-autoupdate run
    depends_on:
      - clickhouse_gateway_api

  redis:
    image: redis:7
    container_name: redis_local
    hostname: redis
    networks:
      - test_network
    command: >
      sh -c "redis-server --requirepass $REDIS_PASSWORD"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./volumes/redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - tempo
      - loki
    networks:
      - test_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - test_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./volumes/tempo_data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - test_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./volumes/grafana_data:/var/lib/grafana
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus
      - tempo
    networks:
      - test_network

  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    volumes:
      - ./volumes/loki_data:/loki
    networks:
      - test_network

networks:
  test_network:
    external: true


